### PR TITLE
Adopt spotbugs instead of findbugs

### PR DESCRIPTION
**Pull request by chintana**
## Purpose
Findbugs is dead - https://mailman.cs.umd.edu/pipermail/findbugs-discuss/2016-November/004321.html. Also there's no JDK 9 compatible version for findbugs - https://github.com/findbugsproject/findbugs/issues/105.

## Goals
Switch codebase to use spotbugs - https://spotbugs.github.io/spotbugs-maven-plugin/

### CODE REVIEW

**Comment by chintana** [comment]
@hasithaa which commit messages exactly? Commits related to sprintf were merged already. Spotbugs related commits are e76dd9a, 00586ee and ac2c603. Can you elaborate what should be reworded?

**Comment by chintana** [comment]
BTW I've rebased my local master branch to upstream master. Not sure why the merged changes also showing up in this.

**Comment by hasithaa** [comment]
@chintana, Commits related to sprintf are not according to standard. If that the case, you may have to cherrypick your commits and send a new PR.

**Comment by chintana** [comment]
Cool. New PR #5009

**Comment by hasithaa** [comment]
Closing this PR since New PR is #5009

**Pull request closed without merging**
